/// Dictionnaire de traductions simple (fr / en / ar).
/// Pour un projet de plus grande envergure, migrer vers flutter_localizations + fichiers .arb.
class AppStrings {
  static const Map<String, Map<String, String>> _dict = {
    'fr': {
      'welcome_title': 'Bienvenue sur Cervix Health',
      'welcome_subtitle': 'Prévention et suivi du cancer du col de l\'utérus',
      'select_profile': 'Sélectionnez votre profil',
      'profile_patient': 'Patiente',
      'profile_personnel': 'Personnel de santé',
      'login': 'Connexion',
      'signup': 'Inscription',
      'username': 'Nom d\'utilisateur',
      'password': 'Mot de passe',
      'confirm_password': 'Confirmer le mot de passe',
      'first_name': 'Prénom',
      'last_name': 'Nom',
      'age': 'Âge',
      'gender': 'Sexe',
      'contact': 'Contact',
      'employer_facility': 'Structure sanitaire employeuse',
      'start_year': 'Année de début de fonction',
      'position': 'Poste occupé',
      'education_level': 'Niveau d\'études',
      'submit': 'Valider',
      'required_field': 'Ce champ est requis',
      'passwords_dont_match': 'Les mots de passe ne correspondent pas',
      'invalid_number': 'Nombre invalide',
      'error_username_taken': 'Ce nom d\'utilisateur existe déjà',
      'error_login_failed': 'Nom d\'utilisateur ou mot de passe incorrect',
      'male': 'Masculin',
      'female': 'Féminin',
      'logout': 'Déconnexion',
      'module_introduction': 'Introduction',
      'module_risk_factors': 'Facteurs de risque',
      'module_screening_request': 'Demande de dépistage',
      'module_tracking': 'Suivi',
      'module_messaging': 'Messagerie',
      'module_community': 'Communauté',
      'introduction_title': 'Cancer du col de l\'utérus : les bases',
      'introduction_body_patient':
          'Le cancer du col de l\'utérus se développe lentement, souvent à partir d\'une infection persistante au papillomavirus humain (HPV). Détecté tôt grâce à un dépistage régulier, il se soigne très bien. Les principaux facteurs de risque incluent l\'absence de dépistage, de multiples partenaires sexuels, le tabagisme et un système immunitaire affaibli. Un dépistage régulier (test VIA/VILI, frottis ou test HPV selon les moyens disponibles) permet de détecter des lésions précancéreuses avant qu\'elles n\'évoluent en cancer.',
      'introduction_body_personnel':
          'En tant que personnel de santé, votre rôle est central dans la prévention du cancer du col de l\'utérus : sensibilisation des patientes, réalisation du dépistage (VIA/VILI, frottis, test HPV), orientation vers un traitement adapté en cas de lésion précancéreuse, et suivi rigoureux des patientes dépistées. La détection précoce reste le levier le plus efficace pour réduire la mortalité liée à cette maladie, en particulier dans les zones à ressources limitées.',
      'risk_factors_title': 'Analyse des facteurs de risque',
      'risk_factors_instruction': 'Répondez par oui ou non à chaque question :',
      'risk_ratio_result': 'Votre ratio de facteurs de risque est de',
      'risk_ratio_advice_high':
          'Ce ratio suggère un niveau de risque à surveiller. Il est recommandé de demander un dépistage.',
      'risk_ratio_advice_low':
          'Votre niveau de risque apparent est faible, mais un dépistage régulier reste recommandé.',
      'request_screening_now': 'Demander un dépistage',
      'screening_request_title': 'Demande de dépistage',
      'select_hospital': 'Sélectionnez un établissement',
      'search_hospital': 'Rechercher un établissement...',
      'search_personnel': 'Rechercher du personnel pour orientation',
      'request_sent': 'Votre demande de dépistage a été envoyée',
      'tracking_title': 'Suivi du dépistage',
      'no_requests_yet': 'Aucune demande de dépistage pour le moment',
      'status_pending': 'En attente',
      'status_scheduled': 'Planifié',
      'status_done': 'Réalisé',
      'status_cancelled': 'Annulé',
      'next_appointment': 'Prochain rendez-vous',
      'technique_used': 'Technique utilisée',
      'result_label': 'Résultat',
      'messaging_title': 'Messagerie',
      'no_conversations': 'Aucune conversation pour le moment',
      'type_message': 'Écrire un message...',
      'send': 'Envoyer',
      'community_title': 'Communauté',
      'write_post': 'Partager quelque chose avec la communauté...',
      'post': 'Publier',
      'no_posts_yet': 'Aucune publication pour le moment',
      'personnel_home_title': 'Espace personnel de santé',
      'screening_requests_received': 'Demandes de dépistage reçues',
      'patient_tracking': 'Suivi des patientes',
      'no_screening_requests': 'Aucune demande reçue pour le moment',
      'update_request': 'Mettre à jour la demande',
      'ai_analysis_placeholder':
          'L\'analyse assistée par IA des images VIA/VILI sera disponible prochainement. Vous pouvez saisir le résultat manuellement pour l\'instant.',
      'save': 'Enregistrer',
      'select_status': 'Statut',
      'select_language': 'Langue',
      'french': 'Français',
      'english': 'English',
      'arabic': 'العربية',
      'welcome_back': 'Bon retour',
      'no_account_question': 'Pas encore de compte ? Inscrivez-vous',
      'have_account_question': 'Déjà inscrit ? Connectez-vous',
      'contact_patient': 'Contacter la patiente',
      'no_personnel_available': 'Aucun personnel disponible pour le moment',
      'date_label': 'Date',
    },
    'en': {
      'welcome_title': 'Welcome to Cervix Health',
      'welcome_subtitle': 'Cervical cancer prevention and follow-up',
      'select_profile': 'Select your profile',
      'profile_patient': 'Patient',
      'profile_personnel': 'Health staff',
      'login': 'Log in',
      'signup': 'Sign up',
      'username': 'Username',
      'password': 'Password',
      'confirm_password': 'Confirm password',
      'first_name': 'First name',
      'last_name': 'Last name',
      'age': 'Age',
      'gender': 'Gender',
      'contact': 'Contact',
      'employer_facility': 'Employing health facility',
      'start_year': 'Year started position',
      'position': 'Position held',
      'education_level': 'Education level',
      'submit': 'Submit',
      'required_field': 'This field is required',
      'passwords_dont_match': 'Passwords do not match',
      'invalid_number': 'Invalid number',
      'error_username_taken': 'This username already exists',
      'error_login_failed': 'Incorrect username or password',
      'male': 'Male',
      'female': 'Female',
      'logout': 'Log out',
      'module_introduction': 'Introduction',
      'module_risk_factors': 'Risk factors',
      'module_screening_request': 'Screening request',
      'module_tracking': 'Tracking',
      'module_messaging': 'Messaging',
      'module_community': 'Community',
      'introduction_title': 'Cervical cancer: the basics',
      'introduction_body_patient':
          'Cervical cancer develops slowly, often from a persistent human papillomavirus (HPV) infection. Detected early through regular screening, it is very treatable. Main risk factors include lack of screening, multiple sexual partners, smoking, and a weakened immune system. Regular screening (VIA/VILI, Pap smear, or HPV test depending on available resources) helps detect precancerous lesions before they progress to cancer.',
      'introduction_body_personnel':
          'As a health worker, your role is central to cervical cancer prevention: raising patient awareness, performing screening (VIA/VILI, Pap smear, HPV test), referring patients to appropriate treatment when precancerous lesions are found, and rigorously following up screened patients. Early detection remains the most effective lever to reduce mortality from this disease, especially in resource-limited areas.',
      'risk_factors_title': 'Risk factor analysis',
      'risk_factors_instruction': 'Answer yes or no to each question:',
      'risk_ratio_result': 'Your risk factor ratio is',
      'risk_ratio_advice_high':
          'This ratio suggests a risk level worth monitoring. It is recommended to request a screening.',
      'risk_ratio_advice_low':
          'Your apparent risk level is low, but regular screening is still recommended.',
      'request_screening_now': 'Request a screening',
      'screening_request_title': 'Screening request',
      'select_hospital': 'Select a facility',
      'search_hospital': 'Search for a facility...',
      'search_personnel': 'Search for staff for referral',
      'request_sent': 'Your screening request has been sent',
      'tracking_title': 'Screening tracking',
      'no_requests_yet': 'No screening request yet',
      'status_pending': 'Pending',
      'status_scheduled': 'Scheduled',
      'status_done': 'Done',
      'status_cancelled': 'Cancelled',
      'next_appointment': 'Next appointment',
      'technique_used': 'Technique used',
      'result_label': 'Result',
      'messaging_title': 'Messaging',
      'no_conversations': 'No conversations yet',
      'type_message': 'Type a message...',
      'send': 'Send',
      'community_title': 'Community',
      'write_post': 'Share something with the community...',
      'post': 'Post',
      'no_posts_yet': 'No posts yet',
      'personnel_home_title': 'Health staff area',
      'screening_requests_received': 'Screening requests received',
      'patient_tracking': 'Patient tracking',
      'no_screening_requests': 'No requests received yet',
      'update_request': 'Update request',
      'ai_analysis_placeholder':
          'AI-assisted analysis of VIA/VILI images will be available soon. You can enter the result manually for now.',
      'save': 'Save',
      'select_status': 'Status',
      'select_language': 'Language',
      'french': 'Français',
      'english': 'English',
      'arabic': 'العربية',
      'welcome_back': 'Welcome back',
      'no_account_question': 'No account yet? Sign up',
      'have_account_question': 'Already have an account? Log in',
      'contact_patient': 'Contact patient',
      'no_personnel_available': 'No staff available at the moment',
      'date_label': 'Date',
    },
    'ar': {
      'welcome_title': 'مرحبًا بك في Cervix Health',
      'welcome_subtitle': 'الوقاية من سرطان عنق الرحم ومتابعته',
      'select_profile': 'اختر ملفك الشخصي',
      'profile_patient': 'مريضة',
      'profile_personnel': 'طاقم صحي',
      'login': 'تسجيل الدخول',
      'signup': 'إنشاء حساب',
      'username': 'اسم المستخدم',
      'password': 'كلمة المرور',
      'confirm_password': 'تأكيد كلمة المرور',
      'first_name': 'الاسم الأول',
      'last_name': 'اسم العائلة',
      'age': 'العمر',
      'gender': 'الجنس',
      'contact': 'وسيلة الاتصال',
      'employer_facility': 'المنشأة الصحية التابع لها',
      'start_year': 'سنة بدء العمل',
      'position': 'المنصب',
      'education_level': 'المستوى الدراسي',
      'submit': 'تأكيد',
      'required_field': 'هذا الحقل مطلوب',
      'passwords_dont_match': 'كلمتا المرور غير متطابقتين',
      'invalid_number': 'رقم غير صالح',
      'error_username_taken': 'اسم المستخدم هذا موجود بالفعل',
      'error_login_failed': 'اسم المستخدم أو كلمة المرور غير صحيحة',
      'male': 'ذكر',
      'female': 'أنثى',
      'logout': 'تسجيل الخروج',
      'module_introduction': 'مقدمة',
      'module_risk_factors': 'عوامل الخطر',
      'module_screening_request': 'طلب فحص',
      'module_tracking': 'المتابعة',
      'module_messaging': 'الرسائل',
      'module_community': 'المجتمع',
      'introduction_title': 'سرطان عنق الرحم: الأساسيات',
      'introduction_body_patient':
          'يتطور سرطان عنق الرحم ببطء، وغالبًا ما ينتج عن عدوى مستمرة بفيروس الورم الحليمي البشري. عند اكتشافه مبكرًا عبر الفحص المنتظم، يمكن علاجه بشكل جيد جدًا. تشمل عوامل الخطر الرئيسية عدم الخضوع للفحص، وتعدد الشركاء الجنسيين، والتدخين، وضعف جهاز المناعة. يساعد الفحص المنتظم على اكتشاف الآفات قبل السرطانية قبل تطورها إلى سرطان.',
      'introduction_body_personnel':
          'بصفتك من الطاقم الصحي، يُعد دورك أساسيًا في الوقاية من سرطان عنق الرحم: توعية المريضات، إجراء الفحص، التوجيه نحو العلاج المناسب عند وجود آفات قبل سرطانية، والمتابعة الدقيقة للمريضات. يظل الكشف المبكر أكثر الوسائل فعالية لتقليل الوفيات الناجمة عن هذا المرض.',
      'risk_factors_title': 'تحليل عوامل الخطر',
      'risk_factors_instruction': 'أجب بنعم أو لا على كل سؤال:',
      'risk_ratio_result': 'نسبة عوامل الخطر لديك هي',
      'risk_ratio_advice_high': 'تشير هذه النسبة إلى مستوى خطر يستدعي الانتباه. يُنصح بطلب فحص.',
      'risk_ratio_advice_low': 'مستوى الخطر الظاهر لديك منخفض، لكن يُنصح دائمًا بالفحص المنتظم.',
      'request_screening_now': 'طلب فحص',
      'screening_request_title': 'طلب فحص',
      'select_hospital': 'اختر منشأة',
      'search_hospital': 'ابحث عن منشأة...',
      'search_personnel': 'البحث عن طاقم صحي للتوجيه',
      'request_sent': 'تم إرسال طلب الفحص الخاص بك',
      'tracking_title': 'متابعة الفحص',
      'no_requests_yet': 'لا يوجد أي طلب فحص حتى الآن',
      'status_pending': 'قيد الانتظار',
      'status_scheduled': 'مُبرمج',
      'status_done': 'تم الإنجاز',
      'status_cancelled': 'ملغى',
      'next_appointment': 'الموعد القادم',
      'technique_used': 'التقنية المستخدمة',
      'result_label': 'النتيجة',
      'messaging_title': 'الرسائل',
      'no_conversations': 'لا توجد محادثات بعد',
      'type_message': 'اكتب رسالة...',
      'send': 'إرسال',
      'community_title': 'المجتمع',
      'write_post': 'شارك شيئًا مع المجتمع...',
      'post': 'نشر',
      'no_posts_yet': 'لا توجد منشورات بعد',
      'personnel_home_title': 'فضاء الطاقم الصحي',
      'screening_requests_received': 'طلبات الفحص المستلمة',
      'patient_tracking': 'متابعة المريضات',
      'no_screening_requests': 'لم يتم استلام أي طلب بعد',
      'update_request': 'تحديث الطلب',
      'ai_analysis_placeholder':
          'سيتوفر قريبًا التحليل بمساعدة الذكاء الاصطناعي لصور VIA/VILI. يمكنك إدخال النتيجة يدويًا في الوقت الحالي.',
      'save': 'حفظ',
      'select_status': 'الحالة',
      'select_language': 'اللغة',
      'french': 'Français',
      'english': 'English',
      'arabic': 'العربية',
      'welcome_back': 'مرحبًا بعودتك',
      'no_account_question': 'ليس لديك حساب؟ سجّل الآن',
      'have_account_question': 'لديك حساب بالفعل؟ سجّل الدخول',
      'contact_patient': 'التواصل مع المريضة',
      'no_personnel_available': 'لا يوجد طاقم متاح حاليًا',
      'date_label': 'التاريخ',
    },
  };

  static String t(String locale, String key) {
    return _dict[locale]?[key] ?? _dict['fr']?[key] ?? key;
  }

  static bool isRtl(String locale) => locale == 'ar';
}
