/// Dictionnaire de traductions simple (fr / en / ar).
/// Pour un projet de plus grande envergure, migrer vers flutter_localizations + fichiers .arb.
class AppStrings {
  static const Map<String, Map<String, String>> _dict = {
    'fr': {
      'welcome_title': 'Bienvenue sur Cervix Health',
      'welcome_subtitle': 'Prévention et suivi du cancer du col de l\'utérus',
      'select_profile': 'Sélectionnez votre profil',
      'profile_patient': 'Patiente',
      'profile_personnel': 'Personnel de santé',
      'login': 'Connexion',
      'signup': 'Inscription',
      'username': 'Nom d\'utilisateur',
      'password': 'Mot de passe',
      'confirm_password': 'Confirmer le mot de passe',
      'first_name': 'Prénom',
      'last_name': 'Nom',
      'age': 'Âge',
      'gender': 'Sexe',
      'contact': 'Contact',
      'employer_facility': 'Structure sanitaire employeuse',
      'start_year': 'Année de début de fonction',
      'position': 'Poste occupé',
      'education_level': 'Niveau d\'études',
      'submit': 'Valider',
      'required_field': 'Ce champ est requis',
      'passwords_dont_match': 'Les mots de passe ne correspondent pas',
      'invalid_number': 'Nombre invalide',
      'error_username_taken': 'Ce nom d\'utilisateur existe déjà',
      'error_login_failed': 'Nom d\'utilisateur ou mot de passe incorrect',
      'male': 'Masculin',
      'female': 'Féminin',
      'logout': 'Déconnexion',
      'module_introduction': 'Introduction',
      'module_risk_factors': 'Facteurs de risque',
      'module_screening_request': 'Demande de dépistage',
      'module_tracking': 'Suivi',
      'module_messaging': 'Messagerie',
      'module_community': 'Communauté',
      'introduction_title': 'Cancer du col de l\'utérus : les bases',
      'introduction_body_patient':
          'Le cancer du col de l\'utérus est l\'un des cancers les plus fréquents chez la femme, mais aussi l\'un des plus faciles à prévenir. Il se développe très lentement, sur 10 à 20 ans, presque toujours à partir d\'une infection persistante au papillomavirus humain (HPV), un virus courant qui se transmet par contact sexuel. Dans la grande majorité des cas, le corps élimine seul cette infection. Ce n\'est que lorsqu\'elle persiste pendant plusieurs années qu\'elle peut provoquer des lésions précancéreuses au niveau du col de l\'utérus.\n\nLes principaux facteurs de risque sont : l\'absence de dépistage régulier, de multiples partenaires sexuels, un premier rapport sexuel précoce, le tabagisme, un système immunitaire affaibli (VIH notamment), et de multiples grossesses. Un accès limité aux soins de santé augmente également le risque, car il retarde le dépistage.\n\nLa bonne nouvelle : détecté au stade précancéreux, ce cancer se soigne presque toujours très simplement, par un traitement local rapide. C\'est pourquoi le dépistage régulier (technique VIA/VILI, frottis cervico-vaginal ou test HPV selon les moyens disponibles dans votre région) est le geste de prévention le plus important que vous puissiez faire. Il est généralement recommandé tous les 3 à 5 ans à partir de 25-30 ans, mais votre personnel de santé pourra vous conseiller la fréquence adaptée à votre situation.\n\nCette application vous accompagne à chaque étape : comprendre les facteurs de risque, demander un dépistage dans un établissement proche de chez vous, suivre l\'évolution de votre dossier, échanger directement avec du personnel de santé, et partager votre expérience au sein d\'une communauté de soutien.',
      'introduction_body_personnel':
          'En tant que personnel de santé, vous êtes en première ligne dans la lutte contre le cancer du col de l\'utérus, une maladie dont la mortalité pourrait être drastiquement réduite grâce à la prévention. Votre rôle couvre plusieurs dimensions complémentaires.\n\nSensibilisation : informer les patientes sur le virus HPV, les facteurs de risque (absence de dépistage, tabagisme, immunodépression, multiparité, faible accès aux soins) et l\'importance d\'un dépistage régulier, en particulier dans les zones où l\'accès à l\'information est limité.\n\nDépistage : réaliser les examens disponibles selon le plateau technique de votre structure — inspection visuelle à l\'acide acétique (IVA) et au lugol (IVL), frottis cervico-vaginal, ou test HPV — et interpréter correctement les résultats.\n\nPrise en charge : en cas de lésion précancéreuse détectée, orienter rapidement la patiente vers un traitement adapté (cryothérapie, thermocoagulation, ou traitement chirurgical selon la sévérité), car un délai de prise en charge trop long augmente le risque d\'évolution.\n\nSuivi : assurer une continuité rigoureuse des soins, avec des rendez-vous de contrôle planifiés et une traçabilité claire du dossier de chaque patiente.\n\nCette application vous permet de centraliser les demandes de dépistage reçues, de mettre à jour le statut et les résultats de vos patientes, de communiquer directement avec elles, et de partager des retours d\'expérience avec vos pairs via l\'espace communautaire. Une future mise à jour intégrera une aide au diagnostic par intelligence artificielle pour l\'analyse des images VIA/VILI.',
      'risk_factors_title': 'Analyse des facteurs de risque',
      'risk_factors_instruction': 'Répondez par oui ou non à chaque question :',
      'risk_ratio_result': 'Votre ratio de facteurs de risque est de',
      'risk_ratio_advice_high':
          'Ce ratio suggère un niveau de risque à surveiller. Il est recommandé de demander un dépistage.',
      'risk_ratio_advice_low':
          'Votre niveau de risque apparent est faible, mais un dépistage régulier reste recommandé.',
      'request_screening_now': 'Demander un dépistage',
      'screening_request_title': 'Demande de dépistage',
      'select_hospital': 'Sélectionnez un établissement',
      'search_hospital': 'Rechercher un établissement...',
      'search_personnel': 'Rechercher du personnel pour orientation',
      'request_sent': 'Votre demande de dépistage a été envoyée',
      'tracking_title': 'Suivi du dépistage',
      'no_requests_yet': 'Aucune demande de dépistage pour le moment',
      'status_pending': 'En attente',
      'status_scheduled': 'Planifié',
      'status_done': 'Réalisé',
      'status_cancelled': 'Annulé',
      'next_appointment': 'Prochain rendez-vous',
      'technique_used': 'Technique utilisée',
      'result_label': 'Résultat',
      'messaging_title': 'Messagerie',
      'no_conversations': 'Aucune conversation pour le moment',
      'type_message': 'Écrire un message...',
      'send': 'Envoyer',
      'community_title': 'Communauté',
      'write_post': 'Partager quelque chose avec la communauté...',
      'post': 'Publier',
      'no_posts_yet': 'Aucune publication pour le moment',
      'personnel_home_title': 'Espace agent de santé',
      'screening_requests_received': 'Demandes de dépistage reçues',
      'patient_tracking': 'Suivi des patientes',
      'no_screening_requests': 'Aucune demande reçue pour le moment',
      'update_request': 'Mettre à jour la demande',
      'ai_analysis_placeholder':
          'L\'analyse assistée par IA des images VIA/VILI sera disponible prochainement. Vous pouvez saisir le résultat manuellement pour l\'instant.',
      'save': 'Enregistrer',
      'select_status': 'Statut',
      'select_language': 'Langue',
      'french': 'Français',
      'english': 'English',
      'arabic': 'العربية',
      'welcome_back': 'Bon retour',
      'no_account_question': 'Pas encore de compte ? Inscrivez-vous',
      'have_account_question': 'Déjà inscrit ? Connectez-vous',
      'contact_patient': 'Contacter la patiente',
      'no_personnel_available': 'Aucun personnel disponible pour le moment',
      'date_label': 'Date',
      'my_profile': 'Mon profil',
      'change_photo': 'Changer la photo',
      'choose_from_gallery': 'Choisir dans la galerie',
      'take_photo': 'Prendre une photo',
      'remove_photo': 'Retirer la photo',
      'profile_updated': 'Profil mis à jour',
      'personal_info': 'Informations personnelles',
      'email': 'Adresse e-mail',
      'forgot_password': 'Mot de passe oublié ?',
      'reset_password_title': 'Réinitialiser le mot de passe',
      'reset_password_instruction':
          'Saisissez l\'adresse e-mail associée à votre compte. Nous vous enverrons un lien pour créer un nouveau mot de passe.',
      'reset_email_sent':
          'Un e-mail de réinitialisation a été envoyé. Vérifiez votre boîte de réception (et vos spams).',
      'back_to_login': 'Retour à la connexion',
      'error_email_in_use': 'Cette adresse e-mail est déjà utilisée',
      'error_email_not_found': 'Aucun compte associé à cette adresse e-mail',
      'error_wrong_password': 'E-mail ou mot de passe incorrect',
      'error_invalid_email': 'Adresse e-mail invalide',
      'error_weak_password': 'Le mot de passe doit contenir au moins 6 caractères',
      'error_profile_not_found':
          'Compte trouvé mais aucun profil associé à ce type sur cet appareil. Essayez l\'autre profil (patiente/personnel) ou réinscrivez-vous.',
      'generic_error': 'Une erreur est survenue. Vérifiez votre connexion internet et réessayez.',
      'error_email_auth_disabled': 'La connexion par e-mail n\'est pas encore activée sur le serveur. Vérifiez dans Firebase : Authentication > Sign-in method > Email/Password.',
      'no_requests_yet_sub': 'Vos demandes de dépistage apparaîtront ici une fois envoyées.',
      'no_conversations_sub': 'Vos échanges avec les patientes ou le personnel apparaîtront ici.',
      'no_posts_yet_sub': 'Soyez la première personne à partager quelque chose avec la communauté.',
      'no_screening_requests_sub': 'Les demandes envoyées par les patientes apparaîtront ici.',
      'select_country': 'Sélectionnez un pays',
      'select_city': 'Sélectionnez une ville',
      'patient_not_found': 'Profil de la patiente introuvable sur cet appareil.',
      'module_news': 'Actualités',
      'news_title': 'Actualités & Ressources',
      'read_more': 'Lire la source',
      'news_disclaimer': 'Informations issues de communications publiques de l\'OMS et de l\'UNICEF, à titre informatif. Elles ne remplacent pas l\'avis de votre personnel de santé.',
      'could_not_open_link': 'Impossible d\'ouvrir ce lien',
      'appointment_reminder_title': 'Rappel de rendez-vous',
      'appointment_reminder_body_prefix': 'Vous avez un dépistage prévu demain à :',
      'profile_agent': 'Agent de santé',
      'profile_specialiste': 'Spécialiste',
      'profile_admin': 'Administrateur',
      'specialty': 'Spécialité',
      'specialiste_home_title': 'Espace spécialiste',
      'specialiste_dossiers_coming_soon': 'La réception et la validation des dossiers attribués arrivent bientôt dans une prochaine mise à jour.',
      'admin_home_title': 'Espace administrateur',
      'admin_coming_soon': 'L\'espace administrateur (gestion des utilisateurs, des rôles et des structures) sera disponible dans une prochaine mise à jour.',
      'status_screened': 'Dépisté',
      'status_referred': 'Orienté vers spécialiste',
      'status_validated': 'Validé',
      'screening_section_title': 'Résultats du dépistage',
      'via_result': 'Résultat IVA',
      'vili_result': 'Résultat IVL',
      'observations': 'Observations',
      'result_positive': 'Positif',
      'result_negative': 'Négatif',
      'result_doubtful': 'Douteux',
      'screening_saved': 'Résultats du dépistage enregistrés',
      'refer_to_specialist': 'Orienter vers un spécialiste',
      'select_specialist': 'Spécialiste',
      'no_specialist_available': 'Aucun spécialiste disponible pour le moment',
      'referred_to_specialist': 'Dossier orienté vers le spécialiste',
      'specialist_conclusion': 'Conclusion du spécialiste',
      'received_dossiers': 'Dossiers reçus',
      'no_dossiers_yet': 'Aucun dossier reçu pour le moment',
      'no_dossiers_yet_sub': 'Les dossiers orientés vers vous par les agents apparaîtront ici.',
      'my_conclusion': 'Ma conclusion',
      'conclusion': 'Conclusion',
      'validate_dossier': 'Valider le dossier',
      'dossier_validated_message': 'Dossier validé avec succès',
      'dossier_already_validated': 'Ce dossier a déjà été validé.',
      'consent_title': 'Consentement et conditions d\'utilisation',
      'consent_intro': 'Avant de continuer, merci de lire attentivement les informations suivantes sur la manière dont vos données seront traitées.',
      'consent_checkbox_label': 'J\'ai lu et j\'accepte les conditions d\'utilisation et la politique de confidentialité ci-dessus.',
      'consent_must_accept': 'Vous devez accepter les conditions pour continuer.',
      'consent_continue': 'Continuer',
      'specialist_tracking_title': 'Suivi de mes dossiers',
      'email_not_verified_banner': 'Votre adresse e-mail n\'est pas encore vérifiée. Vérifiez votre boîte de réception (et vos spams).',
      'resend_verification_email': 'Renvoyer l\'e-mail',
      'ive_verified_check_now': 'J\'ai vérifié',
      'verification_email_resent': 'E-mail de vérification renvoyé.',
      'email_not_verified_yet': 'Toujours pas vérifiée pour l\'instant.',
      'share_conversation_title': 'Partager avec une patiente',
      'no_linked_patients': 'Aucune patiente commune trouvée pour cette conversation.',
      'stop_sharing': 'Arrêter le partage',
      'sharing_active_with': 'Partagé à partir de maintenant avec :',
      'shared_conversation_title': 'Échanges partagés',
      'no_shared_messages': 'Aucun échange partagé pour l\'instant',
      'no_shared_messages_sub': 'Si un agent ou un spécialiste partage sa conversation à votre sujet, elle apparaîtra ici.',
      'shared_conversation_notice': 'Ceci est un aperçu en lecture seule d\'une conversation entre professionnels de santé, partagée avec vous à leur initiative.',
      'share_details_with_patient': 'Partager ces informations avec la patiente',
      'share_details_with_patient_sub': 'Par défaut, les résultats et observations restent confidentiels entre agent et spécialiste. Activez pour les rendre visibles dans le suivi de la patiente.',
      'clinical_details_confidential': 'Les détails cliniques de ce dossier sont confidentiels pour le moment. L\'équipe médicale les partagera avec vous si nécessaire.',
    },
    'en': {
      'welcome_title': 'Welcome to Cervix Health',
      'welcome_subtitle': 'Cervical cancer prevention and follow-up',
      'select_profile': 'Select your profile',
      'profile_patient': 'Patient',
      'profile_personnel': 'Health staff',
      'login': 'Log in',
      'signup': 'Sign up',
      'username': 'Username',
      'password': 'Password',
      'confirm_password': 'Confirm password',
      'first_name': 'First name',
      'last_name': 'Last name',
      'age': 'Age',
      'gender': 'Gender',
      'contact': 'Contact',
      'employer_facility': 'Employing health facility',
      'start_year': 'Year started position',
      'position': 'Position held',
      'education_level': 'Education level',
      'submit': 'Submit',
      'required_field': 'This field is required',
      'passwords_dont_match': 'Passwords do not match',
      'invalid_number': 'Invalid number',
      'error_username_taken': 'This username already exists',
      'error_login_failed': 'Incorrect username or password',
      'male': 'Male',
      'female': 'Female',
      'logout': 'Log out',
      'module_introduction': 'Introduction',
      'module_risk_factors': 'Risk factors',
      'module_screening_request': 'Screening request',
      'module_tracking': 'Tracking',
      'module_messaging': 'Messaging',
      'module_community': 'Community',
      'introduction_title': 'Cervical cancer: the basics',
      'introduction_body_patient':
          'Cervical cancer is one of the most common cancers in women, but also one of the easiest to prevent. It develops very slowly, over 10 to 20 years, almost always from a persistent human papillomavirus (HPV) infection, a common virus spread through sexual contact. In most cases, the body clears the infection on its own. Only when it persists for several years can it cause precancerous lesions on the cervix.\n\nMain risk factors include: lack of regular screening, multiple sexual partners, early first intercourse, smoking, a weakened immune system (notably HIV), and multiple pregnancies. Limited access to healthcare also increases risk, as it delays screening.\n\nThe good news: detected at the precancerous stage, this cancer is almost always treated very simply, with a quick local procedure. This is why regular screening (VIA/VILI, Pap smear, or HPV test depending on resources available in your area) is the most important preventive action you can take. It is generally recommended every 3 to 5 years from age 25-30, but your health provider can advise the frequency suited to your situation.\n\nThis app supports you at every step: understanding risk factors, requesting screening at a facility near you, tracking your file, communicating directly with health staff, and sharing your experience within a support community.',
      'introduction_body_personnel':
          'As a health worker, you are on the front line in the fight against cervical cancer, a disease whose mortality could be drastically reduced through prevention. Your role covers several complementary dimensions.\n\nAwareness: informing patients about the HPV virus, risk factors (lack of screening, smoking, immunosuppression, multiparity, limited healthcare access) and the importance of regular screening, especially in areas with limited access to information.\n\nScreening: performing the exams available based on your facility\'s equipment — visual inspection with acetic acid (VIA) and Lugol\'s iodine (VILI), Pap smear, or HPV test — and correctly interpreting results.\n\nCare: when a precancerous lesion is detected, quickly referring the patient to appropriate treatment (cryotherapy, thermocoagulation, or surgical treatment depending on severity), since delayed care increases the risk of progression.\n\nFollow-up: ensuring rigorous continuity of care, with scheduled check-up appointments and clear record-keeping for each patient.\n\nThis app lets you centralize screening requests received, update your patients\' status and results, communicate directly with them, and share experience with peers via the community space. A future update will integrate AI-assisted diagnosis for VIA/VILI image analysis.',
      'risk_factors_title': 'Risk factor analysis',
      'risk_factors_instruction': 'Answer yes or no to each question:',
      'risk_ratio_result': 'Your risk factor ratio is',
      'risk_ratio_advice_high':
          'This ratio suggests a risk level worth monitoring. It is recommended to request a screening.',
      'risk_ratio_advice_low':
          'Your apparent risk level is low, but regular screening is still recommended.',
      'request_screening_now': 'Request a screening',
      'screening_request_title': 'Screening request',
      'select_hospital': 'Select a facility',
      'search_hospital': 'Search for a facility...',
      'search_personnel': 'Search for staff for referral',
      'request_sent': 'Your screening request has been sent',
      'tracking_title': 'Screening tracking',
      'no_requests_yet': 'No screening request yet',
      'status_pending': 'Pending',
      'status_scheduled': 'Scheduled',
      'status_done': 'Done',
      'status_cancelled': 'Cancelled',
      'next_appointment': 'Next appointment',
      'technique_used': 'Technique used',
      'result_label': 'Result',
      'messaging_title': 'Messaging',
      'no_conversations': 'No conversations yet',
      'type_message': 'Type a message...',
      'send': 'Send',
      'community_title': 'Community',
      'write_post': 'Share something with the community...',
      'post': 'Post',
      'no_posts_yet': 'No posts yet',
      'personnel_home_title': 'Health agent area',
      'screening_requests_received': 'Screening requests received',
      'patient_tracking': 'Patient tracking',
      'no_screening_requests': 'No requests received yet',
      'update_request': 'Update request',
      'ai_analysis_placeholder':
          'AI-assisted analysis of VIA/VILI images will be available soon. You can enter the result manually for now.',
      'save': 'Save',
      'select_status': 'Status',
      'select_language': 'Language',
      'french': 'Français',
      'english': 'English',
      'arabic': 'العربية',
      'welcome_back': 'Welcome back',
      'no_account_question': 'No account yet? Sign up',
      'have_account_question': 'Already have an account? Log in',
      'contact_patient': 'Contact patient',
      'no_personnel_available': 'No staff available at the moment',
      'date_label': 'Date',
      'my_profile': 'My profile',
      'change_photo': 'Change photo',
      'choose_from_gallery': 'Choose from gallery',
      'take_photo': 'Take a photo',
      'remove_photo': 'Remove photo',
      'profile_updated': 'Profile updated',
      'personal_info': 'Personal information',
      'email': 'Email address',
      'forgot_password': 'Forgot password?',
      'reset_password_title': 'Reset password',
      'reset_password_instruction':
          'Enter the email address linked to your account. We will send you a link to set a new password.',
      'reset_email_sent': 'A reset email has been sent. Check your inbox (and spam folder).',
      'back_to_login': 'Back to login',
      'error_email_in_use': 'This email address is already in use',
      'error_email_not_found': 'No account found for this email address',
      'error_wrong_password': 'Incorrect email or password',
      'error_invalid_email': 'Invalid email address',
      'error_weak_password': 'Password must be at least 6 characters',
      'error_profile_not_found':
          'Account found but no matching profile on this device. Try the other profile type (patient/staff) or sign up again.',
      'generic_error': 'Something went wrong. Check your internet connection and try again.',
      'error_email_auth_disabled': 'Email sign-in is not yet enabled on the server. Check in Firebase: Authentication > Sign-in method > Email/Password.',
      'no_requests_yet_sub': 'Your screening requests will appear here once sent.',
      'no_conversations_sub': 'Your conversations with patients or staff will appear here.',
      'no_posts_yet_sub': 'Be the first to share something with the community.',
      'no_screening_requests_sub': 'Requests sent by patients will appear here.',
      'select_country': 'Select a country',
      'select_city': 'Select a city',
      'patient_not_found': 'Patient profile not found on this device.',
      'module_news': 'News',
      'news_title': 'News & Resources',
      'read_more': 'Read source',
      'news_disclaimer': 'Information based on public WHO and UNICEF communications, for informational purposes. It does not replace advice from your health provider.',
      'could_not_open_link': 'Could not open this link',
      'appointment_reminder_title': 'Appointment reminder',
      'appointment_reminder_body_prefix': 'You have a screening scheduled tomorrow at:',
      'profile_agent': 'Health agent',
      'profile_specialiste': 'Specialist',
      'profile_admin': 'Administrator',
      'specialty': 'Specialty',
      'specialiste_home_title': 'Specialist area',
      'specialiste_dossiers_coming_soon': 'Receiving and validating assigned cases is coming in a future update.',
      'admin_home_title': 'Administrator area',
      'admin_coming_soon': 'The administrator area (user, role, and facility management) will be available in a future update.',
      'status_screened': 'Screened',
      'status_referred': 'Referred to specialist',
      'status_validated': 'Validated',
      'screening_section_title': 'Screening results',
      'via_result': 'VIA result',
      'vili_result': 'VILI result',
      'observations': 'Observations',
      'result_positive': 'Positive',
      'result_negative': 'Negative',
      'result_doubtful': 'Doubtful',
      'screening_saved': 'Screening results saved',
      'refer_to_specialist': 'Refer to a specialist',
      'select_specialist': 'Specialist',
      'no_specialist_available': 'No specialist available at the moment',
      'referred_to_specialist': 'Case referred to the specialist',
      'specialist_conclusion': 'Specialist\'s conclusion',
      'received_dossiers': 'Received cases',
      'no_dossiers_yet': 'No cases received yet',
      'no_dossiers_yet_sub': 'Cases referred to you by agents will appear here.',
      'my_conclusion': 'My conclusion',
      'conclusion': 'Conclusion',
      'validate_dossier': 'Validate case',
      'dossier_validated_message': 'Case successfully validated',
      'dossier_already_validated': 'This case has already been validated.',
      'consent_title': 'Consent and Terms of Use',
      'consent_intro': 'Before continuing, please read the following information carefully about how your data will be processed.',
      'consent_checkbox_label': 'I have read and accept the terms of use and privacy policy above.',
      'consent_must_accept': 'You must accept the terms to continue.',
      'consent_continue': 'Continue',
      'specialist_tracking_title': 'My case tracking',
      'email_not_verified_banner': 'Your email address is not verified yet. Check your inbox (and spam folder).',
      'resend_verification_email': 'Resend email',
      'ive_verified_check_now': 'I\'ve verified',
      'verification_email_resent': 'Verification email resent.',
      'email_not_verified_yet': 'Still not verified yet.',
      'share_conversation_title': 'Share with a patient',
      'no_linked_patients': 'No shared patient found for this conversation.',
      'stop_sharing': 'Stop sharing',
      'sharing_active_with': 'Shared from now on with:',
      'shared_conversation_title': 'Shared exchanges',
      'no_shared_messages': 'No shared exchanges yet',
      'no_shared_messages_sub': 'If an agent or specialist shares their conversation about you, it will appear here.',
      'shared_conversation_notice': 'This is a read-only preview of a conversation between health professionals, shared with you at their initiative.',
      'share_details_with_patient': 'Share these details with the patient',
      'share_details_with_patient_sub': 'By default, results and observations stay confidential between agent and specialist. Enable to make them visible in the patient\'s tracking screen.',
      'clinical_details_confidential': 'The clinical details of this case are currently confidential. The medical team will share them with you if needed.',
    },
    'ar': {
      'welcome_title': 'مرحبًا بك في Cervix Health',
      'welcome_subtitle': 'الوقاية من سرطان عنق الرحم ومتابعته',
      'select_profile': 'اختر ملفك الشخصي',
      'profile_patient': 'مريضة',
      'profile_personnel': 'طاقم صحي',
      'login': 'تسجيل الدخول',
      'signup': 'إنشاء حساب',
      'username': 'اسم المستخدم',
      'password': 'كلمة المرور',
      'confirm_password': 'تأكيد كلمة المرور',
      'first_name': 'الاسم الأول',
      'last_name': 'اسم العائلة',
      'age': 'العمر',
      'gender': 'الجنس',
      'contact': 'وسيلة الاتصال',
      'employer_facility': 'المنشأة الصحية التابع لها',
      'start_year': 'سنة بدء العمل',
      'position': 'المنصب',
      'education_level': 'المستوى الدراسي',
      'submit': 'تأكيد',
      'required_field': 'هذا الحقل مطلوب',
      'passwords_dont_match': 'كلمتا المرور غير متطابقتين',
      'invalid_number': 'رقم غير صالح',
      'error_username_taken': 'اسم المستخدم هذا موجود بالفعل',
      'error_login_failed': 'اسم المستخدم أو كلمة المرور غير صحيحة',
      'male': 'ذكر',
      'female': 'أنثى',
      'logout': 'تسجيل الخروج',
      'module_introduction': 'مقدمة',
      'module_risk_factors': 'عوامل الخطر',
      'module_screening_request': 'طلب فحص',
      'module_tracking': 'المتابعة',
      'module_messaging': 'الرسائل',
      'module_community': 'المجتمع',
      'introduction_title': 'سرطان عنق الرحم: الأساسيات',
      'introduction_body_patient':
          'يُعد سرطان عنق الرحم من أكثر أنواع السرطان شيوعًا لدى النساء، لكنه أيضًا من أسهلها وقايةً. يتطور ببطء شديد على مدى 10 إلى 20 عامًا، وينتج في معظم الحالات عن عدوى مستمرة بفيروس الورم الحليمي البشري، وهو فيروس شائع ينتقل عن طريق الاتصال الجنسي. في أغلب الحالات، يتخلص الجسم من العدوى تلقائيًا. فقط عندما تستمر العدوى لعدة سنوات يمكن أن تؤدي إلى آفات قبل سرطانية في عنق الرحم.\n\nتشمل عوامل الخطر الرئيسية: عدم الخضوع للفحص المنتظم، تعدد الشركاء الجنسيين، العلاقة الجنسية الأولى المبكرة، التدخين، ضعف جهاز المناعة (خاصة فيروس نقص المناعة البشرية)، وتعدد حالات الحمل. كما يزيد ضعف الوصول إلى الرعاية الصحية من الخطر لأنه يؤخر الفحص.\n\nالخبر الجيد: عند اكتشافه في المرحلة قبل السرطانية، يُعالج هذا السرطان غالبًا بإجراء موضعي بسيط وسريع. لهذا السبب يُعد الفحص المنتظم (تقنية VIA/VILI أو مسحة عنق الرحم أو فحص فيروس الورم الحليمي حسب الإمكانيات المتاحة في منطقتك) أهم إجراء وقائي يمكنك القيام به. يُنصح به عادة كل 3 إلى 5 سنوات ابتداءً من سن 25-30 عامًا، لكن يمكن لطاقمك الصحي تحديد الوتيرة المناسبة لحالتك.\n\nيرافقك هذا التطبيق في كل خطوة: فهم عوامل الخطر، طلب فحص في منشأة قريبة منك، متابعة ملفك، التواصل مباشرة مع الطاقم الصحي، ومشاركة تجربتك ضمن مجتمع داعم.',
      'introduction_body_personnel':
          'بصفتك من الطاقم الصحي، أنت في الخط الأمامي لمكافحة سرطان عنق الرحم، وهو مرض يمكن تقليل وفياته بشكل كبير بفضل الوقاية. يشمل دورك عدة جوانب متكاملة.\n\nالتوعية: إعلام المريضات بفيروس الورم الحليمي البشري، وعوامل الخطر (عدم الفحص، التدخين، ضعف المناعة، تعدد الولادات، ضعف الوصول إلى الرعاية)، وأهمية الفحص المنتظم، خاصة في المناطق التي يقل فيها الوصول إلى المعلومة.\n\nالفحص: إجراء الفحوصات المتاحة حسب إمكانيات منشأتكم — الفحص البصري بحمض الخل ومحلول لوغول، مسحة عنق الرحم، أو فحص فيروس الورم الحليمي — وتفسير النتائج بشكل صحيح.\n\nالعلاج: عند اكتشاف آفة قبل سرطانية، يجب توجيه المريضة بسرعة نحو العلاج المناسب (العلاج بالتبريد، أو التخثير الحراري، أو العلاج الجراحي حسب شدة الحالة)، لأن تأخر العلاج يزيد من خطر التطور.\n\nالمتابعة: ضمان استمرارية دقيقة للرعاية، مع مواعيد مراقبة مبرمجة وتوثيق واضح لملف كل مريضة.\n\nيتيح لك هذا التطبيق تجميع طلبات الفحص المستلمة، وتحديث حالة ونتائج مريضاتك، والتواصل معهن مباشرة، ومشاركة الخبرات مع زملائك عبر فضاء المجتمع. سيتم لاحقًا دمج مساعدة بالذكاء الاصطناعي لتحليل صور VIA/VILI.',
      'risk_factors_title': 'تحليل عوامل الخطر',
      'risk_factors_instruction': 'أجب بنعم أو لا على كل سؤال:',
      'risk_ratio_result': 'نسبة عوامل الخطر لديك هي',
      'risk_ratio_advice_high': 'تشير هذه النسبة إلى مستوى خطر يستدعي الانتباه. يُنصح بطلب فحص.',
      'risk_ratio_advice_low': 'مستوى الخطر الظاهر لديك منخفض، لكن يُنصح دائمًا بالفحص المنتظم.',
      'request_screening_now': 'طلب فحص',
      'screening_request_title': 'طلب فحص',
      'select_hospital': 'اختر منشأة',
      'search_hospital': 'ابحث عن منشأة...',
      'search_personnel': 'البحث عن طاقم صحي للتوجيه',
      'request_sent': 'تم إرسال طلب الفحص الخاص بك',
      'tracking_title': 'متابعة الفحص',
      'no_requests_yet': 'لا يوجد أي طلب فحص حتى الآن',
      'status_pending': 'قيد الانتظار',
      'status_scheduled': 'مُبرمج',
      'status_done': 'تم الإنجاز',
      'status_cancelled': 'ملغى',
      'next_appointment': 'الموعد القادم',
      'technique_used': 'التقنية المستخدمة',
      'result_label': 'النتيجة',
      'messaging_title': 'الرسائل',
      'no_conversations': 'لا توجد محادثات بعد',
      'type_message': 'اكتب رسالة...',
      'send': 'إرسال',
      'community_title': 'المجتمع',
      'write_post': 'شارك شيئًا مع المجتمع...',
      'post': 'نشر',
      'no_posts_yet': 'لا توجد منشورات بعد',
      'personnel_home_title': 'فضاء العون الصحي',
      'screening_requests_received': 'طلبات الفحص المستلمة',
      'patient_tracking': 'متابعة المريضات',
      'no_screening_requests': 'لم يتم استلام أي طلب بعد',
      'update_request': 'تحديث الطلب',
      'ai_analysis_placeholder':
          'سيتوفر قريبًا التحليل بمساعدة الذكاء الاصطناعي لصور VIA/VILI. يمكنك إدخال النتيجة يدويًا في الوقت الحالي.',
      'save': 'حفظ',
      'select_status': 'الحالة',
      'select_language': 'اللغة',
      'french': 'Français',
      'english': 'English',
      'arabic': 'العربية',
      'welcome_back': 'مرحبًا بعودتك',
      'no_account_question': 'ليس لديك حساب؟ سجّل الآن',
      'have_account_question': 'لديك حساب بالفعل؟ سجّل الدخول',
      'contact_patient': 'التواصل مع المريضة',
      'no_personnel_available': 'لا يوجد طاقم متاح حاليًا',
      'date_label': 'التاريخ',
      'my_profile': 'ملفي الشخصي',
      'change_photo': 'تغيير الصورة',
      'choose_from_gallery': 'اختيار من المعرض',
      'take_photo': 'التقاط صورة',
      'remove_photo': 'إزالة الصورة',
      'profile_updated': 'تم تحديث الملف الشخصي',
      'personal_info': 'المعلومات الشخصية',
      'email': 'البريد الإلكتروني',
      'forgot_password': 'نسيت كلمة المرور؟',
      'reset_password_title': 'إعادة تعيين كلمة المرور',
      'reset_password_instruction':
          'أدخل عنوان البريد الإلكتروني المرتبط بحسابك. سنرسل لك رابطًا لإنشاء كلمة مرور جديدة.',
      'reset_email_sent': 'تم إرسال بريد إلكتروني لإعادة التعيين. تحقق من صندوق الوارد (والبريد غير المرغوب فيه).',
      'back_to_login': 'العودة إلى تسجيل الدخول',
      'error_email_in_use': 'عنوان البريد الإلكتروني هذا مستخدم بالفعل',
      'error_email_not_found': 'لا يوجد حساب مرتبط بهذا البريد الإلكتروني',
      'error_wrong_password': 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
      'error_invalid_email': 'عنوان بريد إلكتروني غير صالح',
      'error_weak_password': 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل',
      'error_profile_not_found':
          'تم العثور على الحساب ولكن لا يوجد ملف شخصي مطابق على هذا الجهاز. جرّب النوع الآخر من الملفات الشخصية أو أعد التسجيل.',
      'generic_error': 'حدث خطأ ما. تحقق من اتصالك بالإنترنت وحاول مرة أخرى.',
      'error_email_auth_disabled': 'تسجيل الدخول بالبريد الإلكتروني غير مفعّل بعد على الخادم. تحقق في Firebase: Authentication > Sign-in method > Email/Password.',
      'no_requests_yet_sub': 'ستظهر طلبات الفحص الخاصة بك هنا بعد إرسالها.',
      'no_conversations_sub': 'ستظهر محادثاتك مع المريضات أو الطاقم الصحي هنا.',
      'no_posts_yet_sub': 'كن أول من يشارك شيئًا مع المجتمع.',
      'no_screening_requests_sub': 'ستظهر هنا الطلبات المرسلة من المريضات.',
      'select_country': 'اختر بلدًا',
      'select_city': 'اختر مدينة',
      'patient_not_found': 'لم يتم العثور على ملف المريضة على هذا الجهاز.',
      'module_news': 'الأخبار',
      'news_title': 'الأخبار والموارد',
      'read_more': 'قراءة المصدر',
      'news_disclaimer': 'معلومات مستندة إلى بيانات عامة صادرة عن منظمة الصحة العالمية واليونيسف، لأغراض إعلامية فقط. لا تغني عن استشارة طاقمك الصحي.',
      'could_not_open_link': 'تعذر فتح هذا الرابط',
      'appointment_reminder_title': 'تذكير بالموعد',
      'appointment_reminder_body_prefix': 'لديك فحص مقرر غدًا في:',
      'profile_agent': 'عون صحي',
      'profile_specialiste': 'أخصائي',
      'profile_admin': 'المدير',
      'specialty': 'التخصص',
      'specialiste_home_title': 'فضاء الأخصائي',
      'specialiste_dossiers_coming_soon': 'استلام الملفات المسندة والتحقق منها سيتوفر قريبًا في تحديث قادم.',
      'admin_home_title': 'فضاء الإدارة',
      'admin_coming_soon': 'سيتوفر فضاء الإدارة (إدارة المستخدمين والأدوار والمنشآت) في تحديث قادم.',
      'status_screened': 'تم الفحص',
      'status_referred': 'موجه إلى أخصائي',
      'status_validated': 'تم التحقق',
      'screening_section_title': 'نتائج الفحص',
      'via_result': 'نتيجة IVA',
      'vili_result': 'نتيجة IVL',
      'observations': 'ملاحظات',
      'result_positive': 'إيجابي',
      'result_negative': 'سلبي',
      'result_doubtful': 'مشكوك فيه',
      'screening_saved': 'تم حفظ نتائج الفحص',
      'refer_to_specialist': 'التوجيه إلى أخصائي',
      'select_specialist': 'الأخصائي',
      'no_specialist_available': 'لا يوجد أخصائي متاح حاليًا',
      'referred_to_specialist': 'تم توجيه الملف إلى الأخصائي',
      'specialist_conclusion': 'استنتاج الأخصائي',
      'received_dossiers': 'الملفات المستلمة',
      'no_dossiers_yet': 'لم يتم استلام أي ملف بعد',
      'no_dossiers_yet_sub': 'ستظهر هنا الملفات الموجهة إليك من قبل الأعوان.',
      'my_conclusion': 'استنتاجي',
      'conclusion': 'الاستنتاج',
      'validate_dossier': 'التحقق من الملف',
      'dossier_validated_message': 'تم التحقق من الملف بنجاح',
      'dossier_already_validated': 'تم التحقق من هذا الملف بالفعل.',
      'consent_title': 'الموافقة وشروط الاستخدام',
      'consent_intro': 'قبل المتابعة، يرجى قراءة المعلومات التالية بعناية حول كيفية معالجة بياناتك.',
      'consent_checkbox_label': 'لقد قرأت ووافقت على شروط الاستخدام وسياسة الخصوصية أعلاه.',
      'consent_must_accept': 'يجب عليك قبول الشروط للمتابعة.',
      'consent_continue': 'متابعة',
      'specialist_tracking_title': 'متابعة ملفاتي',
      'email_not_verified_banner': 'لم يتم التحقق من عنوان بريدك الإلكتروني بعد. تحقق من صندوق الوارد (والبريد غير المرغوب فيه).',
      'resend_verification_email': 'إعادة إرسال البريد',
      'ive_verified_check_now': 'لقد تحققت',
      'verification_email_resent': 'تم إعادة إرسال بريد التحقق.',
      'email_not_verified_yet': 'لم يتم التحقق بعد.',
      'share_conversation_title': 'المشاركة مع مريضة',
      'no_linked_patients': 'لم يتم العثور على مريضة مشتركة لهذه المحادثة.',
      'stop_sharing': 'إيقاف المشاركة',
      'sharing_active_with': 'تتم المشاركة من الآن مع:',
      'shared_conversation_title': 'المحادثات المشتركة',
      'no_shared_messages': 'لا توجد محادثات مشتركة حتى الآن',
      'no_shared_messages_sub': 'إذا شارك عون صحي أو أخصائي محادثته بخصوصك، ستظهر هنا.',
      'shared_conversation_notice': 'هذه معاينة للقراءة فقط لمحادثة بين مهنيين صحيين، تمت مشاركتها معك بمبادرة منهم.',
      'share_details_with_patient': 'مشاركة هذه المعلومات مع المريضة',
      'share_details_with_patient_sub': 'بشكل افتراضي، تبقى النتائج والملاحظات سرية بين العون والأخصائي. فعّل هذا الخيار لجعلها مرئية في متابعة المريضة.',
      'clinical_details_confidential': 'التفاصيل السريرية لهذا الملف سرية حاليًا. سيشاركها معك الفريق الطبي عند الحاجة.',
    },
  };

  static String t(String locale, String key) {
    return _dict[locale]?[key] ?? _dict['fr']?[key] ?? key;
  }

  static bool isRtl(String locale) => locale == 'ar';
}
