name: cervix_health
description: "Application mobile Cervix Health - dépistage et suivi du cancer du col de l'utérus"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  http: ^1.2.2
  url_launcher: ^6.3.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#0F8B8D"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"

flutter:
  uses-material-design: true
